services:
  - type: web
    name: langquest-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: langquest-db
          property: connectionString
    autoDeploy: true
